version: '3'

services:
  Db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "bmp280admin"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: {}